In [2]:
import pandas as pd
X={"A":[1,2,3,4,5], "B":[10,20,30,40,50], "C":[5,4,3,2,1]}
X = pd.DataFrame(X)
print(X)

   A   B  C
0  1  10  5
1  2  20  4
2  3  30  3
3  4  40  2
4  5  50  1


In [5]:
print(type(X.columns))

<class 'pandas.core.indexes.base.Index'>


In [7]:
import numpy as np
x=np.arange(64).reshape(4,4,4)
print(x.shape)

(4, 4, 4)


In [8]:
print(x[1])

[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
